name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      # Lockfile drift check: ensures package-lock.json matches package.json
      - name: Check lockfile sync
        run: |
          npm install --package-lock-only --ignore-scripts
          git diff --exit-code package-lock.json || (echo "package-lock.json is out of sync with package.json. Run 'npm install' locally and commit the lockfile." && exit 1)
          git checkout -- package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run type-check
